### ISSUE TITLE
Subscription dropped

### ISSUE THREAD

**Issue by bidva** [nicdex/node-eventstore-client#57]
Any idea why do I get this ?  it's happening when I connect my local application to aws evetstore

```
2018-07-06T16:44:25.901Z Subscription dropped: catchUpError Error: Retry limit reached. Operation: Operation ReadAllEventsForwardOperation (1db424ae-311f-410c-970f-069e7eccf422): Position: {"commitPosition":{"low":0,"high":0,"unsigned":false},"preparePosition":{"low":0,"high":0,"unsigned":false}}, MaxCount: 500, ResolveLinkTos: false, RequireMaster: true, retry count: 10, created: 16:43:46.794, last updated: 16:44:22.706, RetryCount: 10
    at OperationsManager.module.exports.OperationsManager.scheduleOperationRetry (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:4319:30)
    at /Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:4285:10
    at Array.forEach (<anonymous>)
    at OperationsManager.module.exports.OperationsManager.checkTimeoutsAndRetry (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:4284:19)
    at EventStoreConnectionLogicHandler.module.exports.EventStoreConnectionLogicHandler._goToConnectedState (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3422:22)
    at EventStoreConnectionLogicHandler.module.exports.EventStoreConnectionLogicHandler._handleTcpPackage (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3525:12)
    at /Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3095:10
    at Immediate._handlers.(anonymous function) (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3749:7)
    at runCallback (timers.js:764:11)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
internal/process/warning.js:18 (node:55019) UnhandledPromiseRejectionWarning: Error: Retry limit reached. Operation: Operation ReadAllEventsForwardOperation (1db424ae-311f-410c-970f-069e7eccf422): Position: {"commitPosition":{"low":0,"high":0,"unsigned":false},"preparePosition":{"low":0,"high":0,"unsigned":false}}, MaxCount: 500, ResolveLinkTos: false, RequireMaster: true, retry count: 10, created: 16:43:46.794, last updated: 16:44:22.706, RetryCount: 10
    at OperationsManager.module.exports.OperationsManager.scheduleOperationRetry (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:4319:30)
    at /Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:4285:10
    at Array.forEach (<anonymous>)
    at OperationsManager.module.exports.OperationsManager.checkTimeoutsAndRetry (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:4284:19)
    at EventStoreConnectionLogicHandler.module.exports.EventStoreConnectionLogicHandler._goToConnectedState (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3422:22)
    at EventStoreConnectionLogicHandler.module.exports.EventStoreConnectionLogicHandler._handleTcpPackage (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3525:12)
    at /Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3095:10
    at Immediate._handlers.(anonymous function) (/Users/amirb/source/krs-oc-sync/node_modules/node-eventstore-client/lib/dist.js:3749:7)
    at runCallback (timers.js:764:11)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

**Comment by nicdex** [comment]
I don't have enough data to determine what is wrong.

What I can tell you is that for some reason the client doesn't receive any response from the EventStore within the given timeout (which is 7 seconds by default) and it happens 10 times (which is the limit of retries) so it fails with an Error.

It seems that the client is not able to receive data starting from the beginning, position it tries to read is 0.

I would look into the EventStore logs, there should be information in there related to this issue.

**Comment by dasjestyr** [comment]
For what it's worth, this exact same thing happens with the C# client and oftentimes, there is no error. Greg recommends increasing the heartbeat timeout to > 1s, but it still happens from time to time.

**Comment by nicdex** [comment]
Closing this issue since there is no activity on it and it's also a known issue of the original client which this project is a port of.
